# example Kubernetes deployment manifest
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-zeljana
  labels:
    app: app-zeljana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-zeljana
  template:
    metadata:
      labels:
        app: app-zeljana
    spec:
      containers:
        - name: app-zeljana
          image: zeljana01/final-project:latest
          ports:
            - containerPort: 4000
          readinessProbe:
            httpGet:
              path: /
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 20
